name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven (skip tests)
        run: ./mvnw clean package -DskipTests  # Empaqueta la aplicación y omite los tests
        working-directory: demo  # Asegúrate de que "demo" sea el directorio correcto

      - name: Check Docker and Docker Compose versions
        run: |
          docker --version
          docker compose version

      - name: Build Docker image and run Docker Compose
        run: |
          docker compose up --build -d
        working-directory: demo

      - name: Run Spring Boot application
        run: ./mvnw spring-boot:run  # Corre la aplicación usando Spring Boot
        working-directory: demo

      - name: Stop and clean Docker Compose
        run: |
          docker compose down
        working-directory: demo

      - name: Remove dangling images and containers
        run: |
          docker system prune -f
