name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Check Docker and Docker Compose versions
      run: |
        docker --version
        docker compose version  # Usa docker compose en lugar de docker-compose

    - name: Build Docker image and run Docker Compose
      run: |
        docker compose up --build -d  # Cambiar docker-compose a docker compose
      working-directory: demo

    - name: Run tests (if applicable)
      run: docker exec java_app java -jar java-app.jar  # Aquí puedes ejecutar tus tests si tienes alguno preparado

    - name: Stop and clean Docker Compose
      run: |
        docker compose down  # Cambiar docker-compose a docker compose
      working-directory: demo

    - name: Remove dangling images and containers
      run: |
        docker system prune -f
